name:                hSMC
version:             0.1.0
github:              "Entze/hSMC"
license:             MIT
author:              "Lukas Grassauer"
maintainer:          "lukas@grassauer"
copyright:           "2021 Lukas Grassauer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Verification

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Entze/hSMC#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - sbv >= 8 && < 9

executables:
  hSMC-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hSMC

tests:
  hSMC-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hSMC
    - sbv >= 8 && < 9
